%  * 
%  * [ ii, jj, vals, dpsidX ] = mexGrinspunPlanar( V, T, kl, ka, isShell, alpha1, normebars);
%  *
%  * Input:
%  *  V       3#vertices vector of vertex position
%  *  T        #E by 4 vertices of elements
%  *  kl       #E length stiffness
%  *  ka   #E Lamé parameter of each element
%  *  Abar
%  *  isShell
%  *  alpha1
%  *  normebars #E by 3 rest edge lengths in the following order |x1-x2|, |x1-x3|, |x2-x3|
%  * 
%  * Output:
%  *  ii         81x#E by 1 row indices for each Hessian bloc in a sparse matrix
%  *  jj         81x#E by 1 col indices for each Hessian block in a sparse matrix
%  *  vals      81x#E by 1 energy Hessian wrt X for each element
%  *  dpsidX     9x#3V by 1 energy gradient
%  *
%  * To compile type: mex -R2018a mexGrinspunPlanar.cpp
%  *
%  * Notes:
%  *
%  * Code generated by energy/mexGrinspunPlanar.m
%  *
%  *========================================================